# Generated by Django 5.2.5 on 2025-09-01 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_ref', models.CharField(help_text='رقم الحجز لدى المزود/الفندق/الطيران', max_length=100)),
                ('customer_display_name', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hotel_name', models.CharField(max_length=150)),
                ('hotel_address', models.CharField(blank=True, max_length=200)),
                ('country', models.CharField(blank=True, max_length=80)),
                ('room_type', models.CharField(blank=True, max_length=100)),
                ('meal_plan', models.CharField(blank=True, max_length=100)),
                ('checkin', models.DateField()),
                ('checkout', models.DateField()),
                ('rooms_count', models.PositiveIntegerField(default=1)),
                ('voucher_code', models.CharField(blank=True, editable=False, max_length=80)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('net_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sell_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_installment', models.BooleanField(default=False)),
                ('remaining_amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('installment_due_date', models.DateField(blank=True, null=True)),
                ('method', models.CharField(choices=[('link', 'Payment Link'), ('bank', 'Bank Transfer'), ('cash', 'Cash')], default='cash', max_length=10)),
                ('payment_link', models.URLField(blank=True)),
                ('proof_file', models.FileField(blank=True, upload_to='payments/')),
                ('voucher_original', models.FileField(blank=True, upload_to='vouchers/')),
                ('invoice_file', models.FileField(blank=True, upload_to='invoices/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking_hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.hotelbooking')),
            ],
        ),
        migrations.CreateModel(
            name='UniBookingCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ub_code', models.CharField(editable=False, max_length=50, unique=True)),
                ('customer_name', models.CharField(max_length=150)),
                ('country_code', models.CharField(help_text='+20 مثلًا', max_length=6)),
                ('mobile', models.CharField(help_text='أرقام فقط بدون مسافات', max_length=20)),
                ('nationality', models.CharField(blank=True, max_length=80)),
                ('contact_source', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('call', 'Call'), ('old', 'Existing Customer')], default='whatsapp', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='core.unibookingcard'),
        ),
    ]
