# Generated by Django 5.2.5 on 2025-09-01 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelbooking',
            name='booking_ref',
            field=models.CharField(help_text='رقم الحجز لدى المزود', max_length=100),
        ),
    ]
