# Generated by Django 5.2.5 on 2025-09-01 20:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_hotelbooking_booking_ref'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotelbooking',
            options={'verbose_name': 'Booking', 'verbose_name_plural': 'Bookings'},
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='booking_ref',
            field=models.CharField(max_length=100, verbose_name='Supplier booking ref'),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='core.unibookingcard', verbose_name='Card'),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='checkin',
            field=models.DateField(verbose_name='Check-in'),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='checkout',
            field=models.DateField(verbose_name='Check-out'),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='country',
            field=models.CharField(blank=True, max_length=80, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='customer_display_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Guest name'),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='hotel_address',
            field=models.CharField(blank=True, max_length=200, verbose_name='Hotel address'),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='hotel_name',
            field=models.CharField(max_length=150, verbose_name='Hotel name'),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='meal_plan',
            field=models.CharField(blank=True, max_length=100, verbose_name='Meal plan'),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='room_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='Room type'),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='rooms_count',
            field=models.PositiveIntegerField(default=1, verbose_name='Rooms'),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='voucher_code',
            field=models.CharField(blank=True, editable=False, max_length=80, verbose_name='Voucher code'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='booking_hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.hotelbooking', verbose_name='Hotel booking'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='installment_due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Installment due date'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='invoice_file',
            field=models.FileField(blank=True, upload_to='invoices/', verbose_name='Invoice file'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='is_installment',
            field=models.BooleanField(default=False, verbose_name='Installment'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('link', 'Payment Link'), ('bank', 'Bank Transfer'), ('cash', 'Cash')], default='cash', max_length=10, verbose_name='Payment method'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='net_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Net price'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Paid amount'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_link',
            field=models.URLField(blank=True, verbose_name='Payment link'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='proof_file',
            field=models.FileField(blank=True, upload_to='payments/', verbose_name='Payment proof (bank/cash)'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='remaining_amount',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Remaining'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='sell_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Sell price'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='voucher_original',
            field=models.FileField(blank=True, upload_to='vouchers/', verbose_name='Original voucher'),
        ),
        migrations.AlterField(
            model_name='unibookingcard',
            name='contact_source',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('call', 'Call'), ('old', 'Existing Customer')], default='whatsapp', max_length=20, verbose_name='Contact source'),
        ),
        migrations.AlterField(
            model_name='unibookingcard',
            name='country_code',
            field=models.CharField(help_text='e.g. +20', max_length=6, verbose_name='Country code'),
        ),
        migrations.AlterField(
            model_name='unibookingcard',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='unibookingcard',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cards', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='unibookingcard',
            name='customer_name',
            field=models.CharField(max_length=150, verbose_name='Customer name'),
        ),
        migrations.AlterField(
            model_name='unibookingcard',
            name='mobile',
            field=models.CharField(help_text='Digits only, no spaces', max_length=20, verbose_name='Mobile number'),
        ),
        migrations.AlterField(
            model_name='unibookingcard',
            name='nationality',
            field=models.CharField(blank=True, max_length=80, verbose_name='Nationality'),
        ),
        migrations.AlterField(
            model_name='unibookingcard',
            name='ub_code',
            field=models.CharField(editable=False, max_length=50, unique=True, verbose_name='UniBooking Code'),
        ),
    ]
