# Generated by Django 5.2.5 on 2025-09-01 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_hotelbooking_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelbooking',
            name='voucher_code',
            field=models.CharField(blank=True, editable=False, max_length=80, unique=True, verbose_name='Voucher code'),
        ),
    ]
