# Generated by Django 5.2.5 on 2025-09-01 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_hotelbooking_voucher_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelbooking',
            name='agent_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Agent'),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='employee_name',
            field=models.CharField(blank=True, editable=False, max_length=150, verbose_name='Employee'),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='room1_names',
            field=models.TextField(blank=True, verbose_name='Room 1 Names'),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='room2_names',
            field=models.TextField(blank=True, verbose_name='Room 2 Names'),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='room3_names',
            field=models.TextField(blank=True, verbose_name='Room 3 Names'),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='room4_names',
            field=models.TextField(blank=True, verbose_name='Room 4 Names'),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='room5_names',
            field=models.TextField(blank=True, verbose_name='Room 5 Names'),
        ),
    ]
