# Generated by Django 5.2.5 on 2025-09-01 22:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_hotelbooking_agent_name_hotelbooking_employee_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelbooking',
            name='agent_name',
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='cancellation_penalty',
            field=models.CharField(blank=True, max_length=200, verbose_name='Cancellation penalty'),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='cancellation_policy',
            field=models.CharField(choices=[('nonref', 'non refundable non amendable'), ('refundable', 'refundable')], default='nonref', max_length=20, verbose_name='Cancellation policy'),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='provider_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Provider'),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='refundable_until',
            field=models.DateField(blank=True, null=True, verbose_name='Refundable until'),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='rooms_count',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Rooms'),
        ),
    ]
