# Generated by Django 5.2.5 on 2025-09-02 09:56

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_hotelbooking_agent_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelbooking',
            name='cancellation_penalty',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='cancellation_policy',
            field=models.CharField(choices=[('nonref', 'non refundable non amendable'), ('refundable', 'refundable')], default='nonref', max_length=20),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.unibookingcard', verbose_name='Card'),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='refundable_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='room1_names',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='room2_names',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='room3_names',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='room4_names',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='room5_names',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='rooms_count',
            field=models.PositiveIntegerField(default=1, verbose_name='Rooms'),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='voucher_code',
            field=models.CharField(blank=True, editable=False, max_length=80, verbose_name='Voucher code'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='net_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Net price'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='sell_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Sell price'),
        ),
        migrations.CreateModel(
            name='FlightBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_ref', models.CharField(max_length=100, verbose_name='Supplier booking ref')),
                ('customer_display_name', models.CharField(blank=True, max_length=150, verbose_name='Guest name')),
                ('provider_name', models.CharField(blank=True, max_length=150, verbose_name='Provider')),
                ('employee_name', models.CharField(blank=True, editable=False, max_length=150, verbose_name='Employee')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('airline', models.CharField(max_length=120)),
                ('pnr', models.CharField(max_length=60)),
                ('from_city', models.CharField(max_length=80)),
                ('to_city', models.CharField(max_length=80)),
                ('depart_date', models.DateField()),
                ('depart_time', models.TimeField(blank=True, null=True)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('return_time', models.TimeField(blank=True, null=True)),
                ('travel_class', models.CharField(blank=True, max_length=40)),
                ('passengers', models.TextField(blank=True)),
                ('voucher_code', models.CharField(blank=True, editable=False, max_length=80)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.unibookingcard', verbose_name='Card')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TransferBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_ref', models.CharField(max_length=100, verbose_name='Supplier booking ref')),
                ('customer_display_name', models.CharField(blank=True, max_length=150, verbose_name='Guest name')),
                ('provider_name', models.CharField(blank=True, max_length=150, verbose_name='Provider')),
                ('employee_name', models.CharField(blank=True, editable=False, max_length=150, verbose_name='Employee')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('pickup', models.CharField(max_length=120)),
                ('dropoff', models.CharField(max_length=120)),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('pax', models.PositiveIntegerField(default=1)),
                ('vehicle_type', models.CharField(blank=True, max_length=80)),
                ('notes', models.TextField(blank=True)),
                ('voucher_code', models.CharField(blank=True, editable=False, max_length=80)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.unibookingcard', verbose_name='Card')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VisaBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_ref', models.CharField(max_length=100, verbose_name='Supplier booking ref')),
                ('customer_display_name', models.CharField(blank=True, max_length=150, verbose_name='Guest name')),
                ('provider_name', models.CharField(blank=True, max_length=150, verbose_name='Provider')),
                ('employee_name', models.CharField(blank=True, editable=False, max_length=150, verbose_name='Employee')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('applicant_names', models.TextField(blank=True)),
                ('nationality', models.CharField(blank=True, max_length=80)),
                ('visa_type', models.CharField(blank=True, max_length=80)),
                ('visa_ref', models.CharField(blank=True, max_length=80)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('voucher_code', models.CharField(blank=True, editable=False, max_length=80)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.unibookingcard', verbose_name='Card')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'abstract': False,
            },
        ),
    ]
