# Generated by Django 5.2.5 on 2025-09-10 23:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_hotelbooking_cancellation_penalty_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flightbooking',
            options={},
        ),
        migrations.AlterModelOptions(
            name='hotelbooking',
            options={},
        ),
        migrations.AlterModelOptions(
            name='transferbooking',
            options={},
        ),
        migrations.AlterModelOptions(
            name='visabooking',
            options={},
        ),
        migrations.RemoveField(
            model_name='flightbooking',
            name='airline',
        ),
        migrations.RemoveField(
            model_name='flightbooking',
            name='customer_display_name',
        ),
        migrations.RemoveField(
            model_name='flightbooking',
            name='depart_time',
        ),
        migrations.RemoveField(
            model_name='flightbooking',
            name='passengers',
        ),
        migrations.RemoveField(
            model_name='flightbooking',
            name='pnr',
        ),
        migrations.RemoveField(
            model_name='flightbooking',
            name='provider_name',
        ),
        migrations.RemoveField(
            model_name='flightbooking',
            name='return_date',
        ),
        migrations.RemoveField(
            model_name='flightbooking',
            name='return_time',
        ),
        migrations.RemoveField(
            model_name='flightbooking',
            name='travel_class',
        ),
        migrations.RemoveField(
            model_name='hotelbooking',
            name='cancellation_penalty',
        ),
        migrations.RemoveField(
            model_name='hotelbooking',
            name='cancellation_policy',
        ),
        migrations.RemoveField(
            model_name='hotelbooking',
            name='customer_display_name',
        ),
        migrations.RemoveField(
            model_name='hotelbooking',
            name='hotel_address',
        ),
        migrations.RemoveField(
            model_name='hotelbooking',
            name='meal_plan',
        ),
        migrations.RemoveField(
            model_name='hotelbooking',
            name='provider_name',
        ),
        migrations.RemoveField(
            model_name='hotelbooking',
            name='refundable_until',
        ),
        migrations.RemoveField(
            model_name='hotelbooking',
            name='room1_names',
        ),
        migrations.RemoveField(
            model_name='hotelbooking',
            name='room2_names',
        ),
        migrations.RemoveField(
            model_name='hotelbooking',
            name='room3_names',
        ),
        migrations.RemoveField(
            model_name='hotelbooking',
            name='room4_names',
        ),
        migrations.RemoveField(
            model_name='hotelbooking',
            name='room5_names',
        ),
        migrations.RemoveField(
            model_name='hotelbooking',
            name='room_type',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='installment_due_date',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='invoice_file',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='is_installment',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='method',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_link',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='proof_file',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='remaining_amount',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='voucher_original',
        ),
        migrations.RemoveField(
            model_name='transferbooking',
            name='customer_display_name',
        ),
        migrations.RemoveField(
            model_name='transferbooking',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='transferbooking',
            name='pax',
        ),
        migrations.RemoveField(
            model_name='transferbooking',
            name='provider_name',
        ),
        migrations.RemoveField(
            model_name='transferbooking',
            name='time',
        ),
        migrations.RemoveField(
            model_name='transferbooking',
            name='vehicle_type',
        ),
        migrations.RemoveField(
            model_name='unibookingcard',
            name='contact_source',
        ),
        migrations.RemoveField(
            model_name='unibookingcard',
            name='country_code',
        ),
        migrations.RemoveField(
            model_name='visabooking',
            name='applicant_names',
        ),
        migrations.RemoveField(
            model_name='visabooking',
            name='customer_display_name',
        ),
        migrations.RemoveField(
            model_name='visabooking',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='visabooking',
            name='issue_date',
        ),
        migrations.RemoveField(
            model_name='visabooking',
            name='provider_name',
        ),
        migrations.RemoveField(
            model_name='visabooking',
            name='visa_ref',
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='net',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='nights',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='sell',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='unibookingcard',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='flightbooking',
            name='booking_ref',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='flightbooking',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.unibookingcard'),
        ),
        migrations.AlterField(
            model_name='flightbooking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='flightbooking',
            name='depart_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flightbooking',
            name='employee_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='flightbooking',
            name='from_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='flightbooking',
            name='to_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='flightbooking',
            name='voucher_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='booking_ref',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.unibookingcard'),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='checkin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='checkout',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='employee_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='hotel_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='rooms_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='voucher_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='booking_hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.hotelbooking'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='net_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='payment',
            name='sell_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='transferbooking',
            name='booking_ref',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transferbooking',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.unibookingcard'),
        ),
        migrations.AlterField(
            model_name='transferbooking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='transferbooking',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transferbooking',
            name='dropoff',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transferbooking',
            name='employee_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transferbooking',
            name='pickup',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transferbooking',
            name='voucher_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='unibookingcard',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='unibookingcard',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='unibookingcard',
            name='customer_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='unibookingcard',
            name='mobile',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='unibookingcard',
            name='nationality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='unibookingcard',
            name='ub_code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='visabooking',
            name='booking_ref',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='visabooking',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.unibookingcard'),
        ),
        migrations.AlterField(
            model_name='visabooking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='visabooking',
            name='employee_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='visabooking',
            name='nationality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='visabooking',
            name='visa_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='visabooking',
            name='voucher_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
