# Generated by Django 5.2.5 on 2025-09-10 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_flightbooking_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unibookingcard',
            name='ub_code',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
    ]
