# Generated by Django 5.2.5 on 2025-09-21 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_unibookingcard_ub_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelbooking',
            name='hotel_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='meal_plan',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='provider_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='room1_names',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='room2_names',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='room3_names',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='room4_names',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='room5_names',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='room_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
