# Generated by Django 5.2.5 on 2025-09-21 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_hotelbooking_hotel_address_hotelbooking_meal_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelbooking',
            name='cancellation_penalty',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='cancellation_policy',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='refundable_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
