# Generated by Django 5.2.5 on 2025-09-21 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_hotelbooking_cancellation_penalty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelbooking',
            name='cancellation_policy',
            field=models.CharField(blank=True, choices=[('refundable', 'Refundable'), ('refundable_with_penalty', 'Refundable with Penalty'), ('non_refundable', 'Non-Refundable')], default='refundable', max_length=50, null=True),
        ),
    ]
