# Generated by Django 5.2.5 on 2025-09-21 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_hotelbooking_cancellation_policy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelbooking',
            name='cancellation_penalty',
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='cancellation_penalty_type',
            field=models.CharField(blank=True, choices=[('percent', 'Percentage (%)'), ('amount', 'Fixed Amount')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='cancellation_penalty_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
