# Generated by Django 5.2.5 on 2025-09-21 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_hotelbooking_cancellation_penalty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='employee_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='installment_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='invoice_file',
            field=models.FileField(blank=True, null=True, upload_to='payments/invoices/'),
        ),
        migrations.AddField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cash', 'كاش'), ('bank', 'تحويل بنكي'), ('link', 'Payment Link')], default='cash', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='proof_file',
            field=models.FileField(blank=True, null=True, upload_to='payments/proofs/'),
        ),
        migrations.AddField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='voucher_original',
            field=models.FileField(blank=True, null=True, upload_to='payments/vouchers/'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='booking_hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.hotelbooking'),
        ),
    ]
