# Generated by Django 5.2.5 on 2025-09-21 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_payment_employee_name_payment_installment_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightbooking',
            name='voucher_code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='voucher_code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='transferbooking',
            name='voucher_code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='visabooking',
            name='voucher_code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
