# Generated by Django 5.2.5 on 2025-09-23 12:04

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_payment_updated_at_payment_profit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='installment_due_date',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='profit',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='proof_file',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='remaining',
        ),
        migrations.AddField(
            model_name='payment',
            name='bank_file',
            field=models.FileField(blank=True, null=True, upload_to='payments/banks/', verbose_name='ملف التحويل البنكي'),
        ),
        migrations.AddField(
            model_name='payment',
            name='installment_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الاستحقاق'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='booking_hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.hotelbooking'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='employee_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='invoice_file',
            field=models.FileField(blank=True, null=True, upload_to='payments/invoices/', verbose_name='الفاتورة / التوقيع'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('كاش', 'كاش'), ('تحويل بنكي', 'تحويل بنكي'), ('رابط دفع', 'رابط دفع'), ('تقسيط', 'تقسيط')], max_length=50, verbose_name='طريقة الدفع'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='المبلغ المدفوع'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_link',
            field=models.URLField(blank=True, null=True, verbose_name='رابط الدفع'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='voucher_original',
            field=models.FileField(blank=True, null=True, upload_to='payments/vouchers/', verbose_name='الفوّتشر الأصلي'),
        ),
    ]
