# Generated by Django 5.2.5 on 2025-09-24 21:07

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_payment_installment_due_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelbooking',
            name='room1_names',
        ),
        migrations.RemoveField(
            model_name='hotelbooking',
            name='room2_names',
        ),
        migrations.RemoveField(
            model_name='hotelbooking',
            name='room3_names',
        ),
        migrations.RemoveField(
            model_name='hotelbooking',
            name='room4_names',
        ),
        migrations.RemoveField(
            model_name='hotelbooking',
            name='room5_names',
        ),
        migrations.AlterField(
            model_name='payment',
            name='bank_file',
            field=models.FileField(blank=True, null=True, upload_to='payments/banks/'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='booking_hotel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.hotelbooking'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='installment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='invoice_file',
            field=models.FileField(blank=True, null=True, upload_to='payments/invoices/'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cash', 'كاش'), ('bank', 'تحويل بنكي'), ('link', 'رابط دفع'), ('installment', 'تقسيط')], max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='voucher_original',
            field=models.FileField(blank=True, null=True, upload_to='payments/vouchers/'),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_names', models.TextField(help_text='أسماء النزلاء في هذه الغرفة، مفصولة بفاصلة')),
                ('hotel_booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='core.hotelbooking')),
            ],
        ),
    ]
