# Generated by Django 5.2.5 on 2025-09-25 11:34

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_hotelbooking_room1_names_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('method', models.CharField(choices=[('cash', 'كاش'), ('bank', 'تحويل بنكي'), ('link', 'رابط دفع'), ('installment', 'تقسيط')], max_length=50)),
                ('note', models.TextField(blank=True, null=True)),
                ('payment_link', models.URLField(blank=True, null=True)),
                ('bank_file', models.FileField(blank=True, null=True, upload_to='card_payments/banks/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_payments', to='core.unibookingcard')),
            ],
        ),
    ]
