# Generated by Django 5.2.5 on 2025-09-25 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_cardpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardpayment',
            name='method',
            field=models.CharField(choices=[('cash', 'كاش'), ('bank', 'تحويل بنكي'), ('link', 'رابط دفع')], max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cash', 'كاش'), ('bank', 'تحويل بنكي'), ('link', 'رابط دفع')], max_length=50),
        ),
    ]
