# Generated by Django 5.2.5 on 2025-09-25 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_cardpayment_method_alter_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cash', 'كاش'), ('bank', 'تحويل بنكي'), ('link', 'رابط دفع'), ('installment', 'تقسيط')], max_length=50),
        ),
        migrations.DeleteModel(
            name='CardPayment',
        ),
    ]
