# Generated by Django 5.2.5 on 2025-09-25 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_payment_method_delete_cardpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightbooking',
            name='airline',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='flightbooking',
            name='invoice_file',
            field=models.FileField(blank=True, null=True, upload_to='flights/invoices/'),
        ),
        migrations.AddField(
            model_name='flightbooking',
            name='net_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='flightbooking',
            name='pnr',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='flightbooking',
            name='sell_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='flightbooking',
            name='voucher_file',
            field=models.FileField(blank=True, null=True, upload_to='flights/vouchers/'),
        ),
    ]
