# Generated by Django 5.2.5 on 2025-09-25 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_flightbooking_airline_flightbooking_invoice_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flightbooking',
            name='depart_date',
        ),
        migrations.RemoveField(
            model_name='flightbooking',
            name='from_city',
        ),
        migrations.RemoveField(
            model_name='flightbooking',
            name='to_city',
        ),
        migrations.AlterField(
            model_name='flightbooking',
            name='airline',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='شركة الطيران ✈️'),
        ),
        migrations.AlterField(
            model_name='flightbooking',
            name='invoice_file',
            field=models.FileField(blank=True, null=True, upload_to='flights/invoices/', verbose_name='الفاتورة'),
        ),
        migrations.AlterField(
            model_name='flightbooking',
            name='net_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='سعر النت 💵'),
        ),
        migrations.AlterField(
            model_name='flightbooking',
            name='pnr',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='PNR'),
        ),
        migrations.AlterField(
            model_name='flightbooking',
            name='sell_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='سعر البيع 💵'),
        ),
        migrations.AlterField(
            model_name='flightbooking',
            name='voucher_file',
            field=models.FileField(blank=True, null=True, upload_to='flights/vouchers/', verbose_name='الفاوتشر'),
        ),
    ]
