# Generated by Django 5.2.5 on 2025-09-25 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_flightbooking_depart_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightbooking',
            name='depart_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flightbooking',
            name='depart_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flightbooking',
            name='flight_class',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='flightbooking',
            name='from_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='flightbooking',
            name='passenger_names',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flightbooking',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flightbooking',
            name='return_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flightbooking',
            name='to_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='flightbooking',
            name='airline',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='flightbooking',
            name='invoice_file',
            field=models.FileField(blank=True, null=True, upload_to='flights/invoices/'),
        ),
        migrations.AlterField(
            model_name='flightbooking',
            name='net_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='flightbooking',
            name='pnr',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='flightbooking',
            name='sell_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='flightbooking',
            name='voucher_file',
            field=models.FileField(blank=True, null=True, upload_to='flights/vouchers/'),
        ),
    ]
