# Generated by Django 5.2.5 on 2025-09-25 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_flightbooking_depart_date_flightbooking_depart_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flightbooking',
            name='depart_date',
        ),
        migrations.RemoveField(
            model_name='flightbooking',
            name='depart_time',
        ),
        migrations.RemoveField(
            model_name='flightbooking',
            name='flight_class',
        ),
        migrations.RemoveField(
            model_name='flightbooking',
            name='from_city',
        ),
        migrations.RemoveField(
            model_name='flightbooking',
            name='passenger_names',
        ),
        migrations.RemoveField(
            model_name='flightbooking',
            name='return_date',
        ),
        migrations.RemoveField(
            model_name='flightbooking',
            name='return_time',
        ),
        migrations.RemoveField(
            model_name='flightbooking',
            name='to_city',
        ),
        migrations.AddField(
            model_name='flightbooking',
            name='payment_file',
            field=models.FileField(blank=True, null=True, upload_to='flights/payments/'),
        ),
        migrations.AddField(
            model_name='flightbooking',
            name='payment_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flightbooking',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'كاش'), ('bank', 'تحويل بنكي'), ('link', 'رابط دفع')], max_length=50, null=True),
        ),
    ]
