# Generated by Django 5.2.5 on 2025-09-26 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_flightbooking_depart_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flightbooking',
            name='booking_ref',
        ),
        migrations.RemoveField(
            model_name='flightbooking',
            name='employee_name',
        ),
        migrations.RemoveField(
            model_name='flightbooking',
            name='voucher_code',
        ),
        migrations.AddField(
            model_name='flightbooking',
            name='booking_code',
            field=models.CharField(blank=True, editable=False, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='flightbooking',
            name='airline',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='flightbooking',
            name='invoice_file',
            field=models.FileField(blank=True, null=True, upload_to='invoices/flights/'),
        ),
        migrations.AlterField(
            model_name='flightbooking',
            name='net_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='flightbooking',
            name='payment_file',
            field=models.FileField(blank=True, null=True, upload_to='payments/flights/'),
        ),
        migrations.AlterField(
            model_name='flightbooking',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'كاش'), ('bank', 'تحويل بنكي'), ('link', 'رابط دفع')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='flightbooking',
            name='pnr',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='flightbooking',
            name='sell_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='flightbooking',
            name='voucher_file',
            field=models.FileField(blank=True, null=True, upload_to='vouchers/flights/'),
        ),
    ]
